-- MySQL Script generated by MySQL Workbench
-- 01/21/25 14:10:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendedor` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(45) NOT NULL,
    `setor` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(45) NOT NULL,
    `email` VARCHAR(45) NOT NULL,
    `senha` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `descricao` VARCHAR(45) NOT NULL,
    `valor` DECIMAL(20, 10) NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `quantidade` INT NOT NULL,
    `vendedor_id` INT NOT NULL,
    `cliente_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`vendedor_id`) REFERENCES `vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produto` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(45) NOT NULL,
    `descricao` VARCHAR(45) NOT NULL,
    `valor` DECIMAL(20, 10) NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `vendedor_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`vendedor_id`) REFERENCES `vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Produto_tem_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produto_tem_pedido` (
    `produto_id` INT NOT NULL,
    `pedido_id` INT NOT NULL,
    PRIMARY KEY (`produto_id`, `pedido_id`),
    FOREIGN KEY (`produto_id`) REFERENCES `produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`pedido_id`) REFERENCES `pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `status_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `status_pedido` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `descricao` VARCHAR(45) NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Pedido_historico_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_historico_status` (
    `pedido_id` INT NOT NULL,
    `status_pedido_id` INT NOT NULL,
    PRIMARY KEY (`pedido_id`, `status_pedido_id`),
    FOREIGN KEY (`pedido_id`) REFERENCES `pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`status_pedido_id`) REFERENCES `status_pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(45) NOT NULL,
    `quantidade` INT NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagamento` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `status` VARCHAR(45) NOT NULL,
    `tipo` ENUM("credito", "debito", "boleto", "pix") NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `pedido_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`pedido_id`) REFERENCES `pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Estoque_tem_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque_tem_produto` (
    `estoque_id` INT NOT NULL,
    `produto_id` INT NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`estoque_id`, `produto_id`),
    FOREIGN KEY (`estoque_id`) REFERENCES `estoque` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`produto_id`) REFERENCES `produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;